import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <header className=" bg-amber-900">
          <div className="flex justify-between items-center py-3 container mx-auto">
            <div>
              <h1 className="text-2xl font-bold">Daily-Dish</h1>{" "}
            </div>
            <div>
              <Link className="btn mr-5" href={"/foods"}>
                Foods
              </Link>
              <Link className="btn" href={"/reviews"}>
                Review
              </Link>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
